apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fullnodes.lino.network.k8s.io
spec:
  group: lino.network.k8s.io
  version: v1
  names:
    kind: Fullnode
    plural: Fullnodes
  scope: Namespaced