/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/lino-network/lino-operator/pkg/apis/samplecrd/v1"
	scheme "github.com/lino-network/lino-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FullnodesGetter has a method to return a FullnodeInterface.
// A group's client should implement this interface.
type FullnodesGetter interface {
	Fullnodes(namespace string) FullnodeInterface
}

// FullnodeInterface has methods to work with Fullnode resources.
type FullnodeInterface interface {
	Create(*v1.Fullnode) (*v1.Fullnode, error)
	Update(*v1.Fullnode) (*v1.Fullnode, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Fullnode, error)
	List(opts metav1.ListOptions) (*v1.FullnodeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Fullnode, err error)
	FullnodeExpansion
}

// fullnodes implements FullnodeInterface
type fullnodes struct {
	client rest.Interface
	ns     string
}

// newFullnodes returns a Fullnodes
func newFullnodes(c *SamplecrdV1Client, namespace string) *fullnodes {
	return &fullnodes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fullnode, and returns the corresponding fullnode object, and an error if there is any.
func (c *fullnodes) Get(name string, options metav1.GetOptions) (result *v1.Fullnode, err error) {
	result = &v1.Fullnode{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fullnodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Fullnodes that match those selectors.
func (c *fullnodes) List(opts metav1.ListOptions) (result *v1.FullnodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FullnodeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fullnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fullnodes.
func (c *fullnodes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fullnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a fullnode and creates it.  Returns the server's representation of the fullnode, and an error, if there is any.
func (c *fullnodes) Create(fullnode *v1.Fullnode) (result *v1.Fullnode, err error) {
	result = &v1.Fullnode{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fullnodes").
		Body(fullnode).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fullnode and updates it. Returns the server's representation of the fullnode, and an error, if there is any.
func (c *fullnodes) Update(fullnode *v1.Fullnode) (result *v1.Fullnode, err error) {
	result = &v1.Fullnode{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fullnodes").
		Name(fullnode.Name).
		Body(fullnode).
		Do().
		Into(result)
	return
}

// Delete takes name of the fullnode and deletes it. Returns an error if one occurs.
func (c *fullnodes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fullnodes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fullnodes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fullnodes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fullnode.
func (c *fullnodes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Fullnode, err error) {
	result = &v1.Fullnode{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fullnodes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
