/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	samplecrdv1 "github.com/lino-network/lino-operator/pkg/apis/samplecrd/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFullnodes implements FullnodeInterface
type FakeFullnodes struct {
	Fake *FakeSamplecrdV1
	ns   string
}

var fullnodesResource = schema.GroupVersionResource{Group: "samplecrd.k8s.io", Version: "v1", Resource: "fullnodes"}

var fullnodesKind = schema.GroupVersionKind{Group: "samplecrd.k8s.io", Version: "v1", Kind: "Fullnode"}

// Get takes name of the fullnode, and returns the corresponding fullnode object, and an error if there is any.
func (c *FakeFullnodes) Get(name string, options v1.GetOptions) (result *samplecrdv1.Fullnode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fullnodesResource, c.ns, name), &samplecrdv1.Fullnode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.Fullnode), err
}

// List takes label and field selectors, and returns the list of Fullnodes that match those selectors.
func (c *FakeFullnodes) List(opts v1.ListOptions) (result *samplecrdv1.FullnodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fullnodesResource, fullnodesKind, c.ns, opts), &samplecrdv1.FullnodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &samplecrdv1.FullnodeList{ListMeta: obj.(*samplecrdv1.FullnodeList).ListMeta}
	for _, item := range obj.(*samplecrdv1.FullnodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fullnodes.
func (c *FakeFullnodes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fullnodesResource, c.ns, opts))

}

// Create takes the representation of a fullnode and creates it.  Returns the server's representation of the fullnode, and an error, if there is any.
func (c *FakeFullnodes) Create(fullnode *samplecrdv1.Fullnode) (result *samplecrdv1.Fullnode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fullnodesResource, c.ns, fullnode), &samplecrdv1.Fullnode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.Fullnode), err
}

// Update takes the representation of a fullnode and updates it. Returns the server's representation of the fullnode, and an error, if there is any.
func (c *FakeFullnodes) Update(fullnode *samplecrdv1.Fullnode) (result *samplecrdv1.Fullnode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fullnodesResource, c.ns, fullnode), &samplecrdv1.Fullnode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.Fullnode), err
}

// Delete takes name of the fullnode and deletes it. Returns an error if one occurs.
func (c *FakeFullnodes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fullnodesResource, c.ns, name), &samplecrdv1.Fullnode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFullnodes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fullnodesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &samplecrdv1.FullnodeList{})
	return err
}

// Patch applies the patch and returns the patched fullnode.
func (c *FakeFullnodes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *samplecrdv1.Fullnode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fullnodesResource, c.ns, name, pt, data, subresources...), &samplecrdv1.Fullnode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.Fullnode), err
}
