/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	samplecrdv1 "github.com/lino-network/lino-operator/pkg/apis/samplecrd/v1"
	versioned "github.com/lino-network/lino-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/lino-network/lino-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/lino-network/lino-operator/pkg/client/listers/samplecrd/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FullnodeInformer provides access to a shared informer and lister for
// Fullnodes.
type FullnodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.FullnodeLister
}

type fullnodeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFullnodeInformer constructs a new informer for Fullnode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFullnodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFullnodeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFullnodeInformer constructs a new informer for Fullnode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFullnodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecrdV1().Fullnodes(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecrdV1().Fullnodes(namespace).Watch(options)
			},
		},
		&samplecrdv1.Fullnode{},
		resyncPeriod,
		indexers,
	)
}

func (f *fullnodeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFullnodeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *fullnodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&samplecrdv1.Fullnode{}, f.defaultInformer)
}

func (f *fullnodeInformer) Lister() v1.FullnodeLister {
	return v1.NewFullnodeLister(f.Informer().GetIndexer())
}
